# note: base environment values are in the hidden and secertly named ".env" file

version: "3"
services:
  minio:
    image: minio/minio
    # Note: the docker image internally always uses 9000 so for this setup it is not really a configuration option
    ports: 
      - "$STORAGE_PORT:9000"
    env_file: 
      .env
    environment:
      MINIO_ACCESS_KEY: "$STORAGE_ACCESS_KEY_ID"
      MINIO_SECRET_KEY: "$STORAGE_ACCESS_KEY"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: minio server /data
  db:
    image: postgres:11-alpine
    env_file:
      .env
    volumes:
      # note that the postgres image defines this volume, so the exact path on the right is important
      - psql_db:/var/lib/postgresql/data
  radiator:
    build: ..
    ports:
      - "$RADIATOR_PORT:$RADIATOR_PORT"
    depends_on:
      - db
      - minio
      - email
    env_file:
      .env
    environment:
      HOST: $RADIATOR_HOST
      PORT: $RADIATOR_PORT
      PUBLIC_PORT: $RADIATOR_PORT
      PUBLIC_SCHEME: $RADIATOR_PUBLIC_SCHEME
      # make sure that local environment variables overwrite the .env based ones
      # docker compose has this weird precedence of .env file over local var
      # but env variables used here on the right hand side will be pulled in from the current environment
      STORAGE_ACCESS_KEY_ID: "$STORAGE_ACCESS_KEY_ID"
      STORAGE_ACCESS_KEY: "$STORAGE_ACCESS_KEY"
  email:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  minio_data:
  minio_config:
  psql_db:
